---
apiVersion: v2
name: app
description: Justice Data Platform application
type: application
version: 0.2.0-rc2
appVersion: 0.2.0-rc2
icon: https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Ministry_of_Justice_logo_%28United_Kingdom%29.svg/611px-Ministry_of_Justice_logo_%28United_Kingdom%29.svg.png
maintainers:
  - name: moj-data-platform-robot
    email: justicedataplatform@justice.gov.uk
