# Generated by Django 6.0.6 on 2026-07-01 14:55

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="oid",
            field=models.UUIDField(
                default="00000000-0000-0000-0000-000000000000",
                help_text="Immutable Microsoft Entra ID object id used as the login identity.",
                unique=True,
                verbose_name="Entra object ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Human-readable name from Entra; not used to sign in.",
                max_length=150,
                verbose_name="display name",
            ),
        ),
    ]
