# Generated by Django 6.0.6 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_historicalprojectuserpermissions_table_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectuserpermissions",
            constraint=models.UniqueConstraint(
                fields=("project", "user"),
                name="uniq_project_user_membership",
            ),
        ),
    ]
