# Generated by Django 6.0.6 on 2026-07-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_projectuserpermissions_unique_project_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="slug",
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
