# Generated by Django 6.0.6 on 2026-07-07 13:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_historicalproject_slug_alter_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
