# Generated by Django 6.0.6 on 2026-07-09 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_historicalproject_uuid_project_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slug",
        ),
    ]
