# Generated by Django 6.0.6 on 2026-07-21 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_add_business_units"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessunit",
            options={"ordering": ["name"]},
        ),
    ]
