# Generated by Django 6.1 on 2026-09-10 14:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_businessunit_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalProjectUserPermissions",
            new_name="HistoricalProjectMembership",
        ),
        migrations.RenameModel(
            old_name="ProjectUserPermissions",
            new_name="ProjectMembership",
        ),
        migrations.AlterModelOptions(
            name="historicalprojectmembership",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project membership",
                "verbose_name_plural": "historical project user permissions",
            },
        ),
    ]
