# Generated by Django 6.1 on 2026-09-10 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_rename_project_memberships"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprojectmembership",
            name="role",
        ),
        migrations.RemoveField(
            model_name="projectmembership",
            name="role",
        ),
    ]
