# Generated by Django 6.1 on 2026-09-10 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_remove_role_from_project_membership"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="historicalprojectmembership",
            table="project_membership_history",
        ),
        migrations.AlterModelTable(
            name="projectmembership",
            table="project_membership",
        ),
    ]
