# Generated by Django 6.1 on 2026-09-11 12:27

from django.db import migrations


def forwards(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        if not project.owner:
            project.owner = project.created_by
            project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_add_project_membership_permission_and_more"),
    ]

    operations = [
        migrations.RunPython(code=forwards, reverse_code=migrations.RunPython.noop),
    ]
