# Generated by Django 6.1 on 2026-09-11 15:08

from django.db import migrations


def grant_existing_members_all_permissions(apps, schema_editor):
    ProjectMembership = apps.get_model("projects", "ProjectMembership")
    ProjectMembershipPermission = apps.get_model(
        "projects",
        "ProjectMembershipPermission",
    )
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="projects",
        model="project",
    )

    permissions = []

    for codename, name in [
        ("manage_api_keys", "Manage API Keys"),
        ("manage_members", "Manage Members"),
    ]:
        permission, _ = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permissions.append(permission)

    assignments = [
        ProjectMembershipPermission(
            membership=membership,
            permission=permission,
            granted_by=None,
        )
        for membership in ProjectMembership.objects.all()
        for permission in permissions
    ]

    ProjectMembershipPermission.objects.bulk_create(
        assignments,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_data_migration_project_owner"),
    ]

    operations = [
        migrations.RunPython(
            grant_existing_members_all_permissions,
            migrations.RunPython.noop,
        ),
    ]
