# Generated by Django 6.1 on 2026-09-11 15:08

from django.db import migrations


def grant_existing_members_all_permissions(apps, schema_editor):
    ProjectMembership = apps.get_model("projects", "ProjectMembership")
    ProjectMembershipPermission = apps.get_model(
        "projects",
        "ProjectMembershipPermission",
    )
    Permission = apps.get_model("auth", "Permission")

    permissions = Permission.objects.filter(
        content_type__app_label="projects",
        content_type__model="project",
        codename__in=[
            "manage_api_keys",
            "manage_members",
        ],
    )

    assignments = []

    for membership in ProjectMembership.objects.all():
        for permission in permissions:
            assignments.append(
                ProjectMembershipPermission(
                    membership=membership,
                    permission=permission,
                    granted_by=None,
                )
            )

    ProjectMembershipPermission.objects.bulk_create(
        assignments,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_data_migration_project_owner"),
    ]

    operations = [
        migrations.RunPython(
            grant_existing_members_all_permissions,
            migrations.RunPython.noop,
        ),
    ]
