# Generated by Django 6.1 on 2026-09-10 16:02

from django.db import migrations


def forwards(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        if not project.owner:
            project.owner = project.created_by
            project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_add_owner_to_project"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
