# Generated by Django 6.1 on 2026-09-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_data_migration_to_populate_owners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="projects.project",
            ),
        ),
    ]
