# Generated by Django 6.1 on 2026-09-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("projects", "0015_rename_memberships_related_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": [
                    ("manage_api_keys", "Manage API Keys"),
                    ("manage_members", "Manage Members"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="historicalprojectmembershippermission",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AlterField(
            model_name="projectmembershippermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_membership_permissions",
                to="auth.permission",
            ),
        ),
    ]
