# Generated by Django 6.1 on 2026-09-11 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("projects", "0016_add_project_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalprojectmembership",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project membership",
                "verbose_name_plural": "historical Project members",
            },
        ),
        migrations.AlterModelOptions(
            name="projectmembership",
            options={"verbose_name_plural": "Project members"},
        ),
        migrations.AlterField(
            model_name="historicalprojectmembershippermission",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={
                    "codename__in": ["manage_api_keys", "manage_members"],
                    "content_type__app_label": "projects",
                    "content_type__model": "project",
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectmembershippermission",
            name="permission",
            field=models.ForeignKey(
                limit_choices_to={
                    "codename__in": ["manage_api_keys", "manage_members"],
                    "content_type__app_label": "projects",
                    "content_type__model": "project",
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_membership_permissions",
                to="auth.permission",
            ),
        ),
    ]
