---
ignore:
  - package:
      location: /usr/bin/pebble # Skipping this binary due to various CVEs

  - vulnerability: CVE-2026-42496
    package:
      name: perl-base
      type: deb

  - vulnerability: CVE-2026-8376
    package:
      name: perl-base
      type: deb

  - vulnerability: CVE-2026-41992
    package:
      name: gzip
      type: deb

  - vulnerability: CVE-2026-5450
    package:
      type: deb
      name: libc-bin|libc-gconv-modules-extra|libc6
    expires: 2026-08-28

  - vulnerability: CVE-2026-4046
    package:
      type: deb
      name: libc-bin|libc-gconv-modules-extra|libc6
    expires: 2026-08-28

  - vulnerability: CVE-2026-5928
    package:
      type: deb
      name: libc-bin|libc-gconv-modules-extra|libc6
    expires: 2026-08-28

  - vulnerability: CVE-2026-5435
    package:
      type: deb
      name: libc-bin|libc-gconv-modules-extra|libc6
    expires: 2026-08-28

  - vulnerability: GHSA-g6cj-pr64-35w5
    package:
      type: python
      name: cryptography
    expires: 2026-08-10

  - vulnerability: GHSA-f2ff-p2ww-7p4p
    package:
      type: python
      name: sqlparse
    expires: 2026-08-20

  - vulnerability: GHSA-prg7-hcfm-mfcr
    package:
      type: python
      name: sqlparse
    expires: 2026-08-20

  - vulnerability: GHSA-pwgv-4x5q-6m9f
    package:
      type: python
      name: sqlparse
    expires: 2026-08-20

  - vulnerability: CVE-2026-54371
    package:
      type: deb
      name: libattr1
    expires: 2026-09-28
