# Generated by Django 6.0.8 on 2026-08-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalkey",
            name="models",
            field=models.JSONField(
                default=list,
                help_text="Model identifiers last successfully applied by this application. Only changes made through this application are captured; the AI Gateway remains the source of truth.",
            ),
        ),
        migrations.AddField(
            model_name="key",
            name="models",
            field=models.JSONField(
                default=list,
                help_text="Model identifiers last successfully applied by this application. Only changes made through this application are captured; the AI Gateway remains the source of truth.",
            ),
        ),
    ]
