---
name: Build and Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build Image
        id: build_image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: Containerfile
          push: false
          load: true
          tags: data_platform_app

      - name: Run Python Tests
        id: run_python_tests
        env:
          NETWORK: default
          IMAGE_TAG: data_platform_app
        run: |
          docker compose --file contrib/docker-compose-test.yml run --rm interfaces
