---
name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04-arm
    permissions:
      code-quality: write
      contents: read
    steps:
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build Image
        id: build_image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: Containerfile
          push: false
          load: true
          tags: data_platform_app

      - name: Run Python Tests
        id: run_python_tests
        env:
          NETWORK: default
          IMAGE_TAG: data_platform_app
        run: |
          mkdir --parent contrib/coverage
          chmod 0777 contrib/coverage

          docker compose --file contrib/docker-compose-test.yml run --rm interfaces

      - name: Upload Test Coverage
        id: upload_test_coverage
        uses: actions/upload-code-coverage@abb5995db9e0199b0e2bb9dbd136fce4cb1ec4d3 # v1.3.0
        with:
          file: contrib/coverage/coverage.xml
          language: Python
          label: code-coverage/pytest
