---
name: Chart Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  chart-release:
    name: Chart Release
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/chart-release.yml@5a78fec83924b266564bef1a9803536a9bd68a1f # v4.0.7
