---
name: Chart Lint

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  chart-lint:
    name: Chart Lint
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/chart-lint.yml@7f9f1fc18fcddd41c08a33be1e4e57cb8065a0cf # v4.0.0
