---
name: Container Scan

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  container-scan:
    name: Container Scan
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/container-scan.yml@6df010e45fdb953369f12ab2bc69107d3c487f15 # v4.0.8
    with:
      containerfile-path: Dockerfile
