---
name: Container Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  container-release:
    name: Container Release
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/container-release.yml@feb7a2d3220db8dcd1b541e43fa5596af398c491 # v4.1.3
    with:
      containerfile-path: Dockerfile
