---
name: Container Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-test:
    name: Container Test
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/container-test.yml@feat/container-test # zizmor: ignore[unpinned-uses]
    with:
      configuration-file: tests/container-structure-test.yml
