---
name: Container Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  container-release:
    name: Container Release
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/container-release.yml@c8dbd40674f1a0401e516e51cd6fa61c7f4fdc23 # v4.1.0
    with:
      containerfile-path: Dockerfile
