---
name: Dependency Review

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/dependency-review.yml@c8dbd40674f1a0401e516e51cd6fa61c7f4fdc23 # v4.1.0
