---
name: Spell Check

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  spell-check:
    name: Spell Check
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/spell-check.yml@c8dbd40674f1a0401e516e51cd6fa61c7f4fdc23 # v4.1.0
