---
name: Spell Check

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  spell-check:
    name: Spell Check
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/spell-check.yml@ff9b59430b75056f2234fc204651ca64c9c4f474 # v4.0.9
