---
name: Spell Check

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  spell-check:
    name: Spell Check
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/spell-check.yml@f48cf9157c3eae2dcecf5173a474577aabcd37a5 # v4.1.2
