---
name: Zizmor

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/zizmor.yml@ff9b59430b75056f2234fc204651ca64c9c4f474 # v4.0.9
