# Generated by Django 6.1 on 2026-08-26 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("project_read", "Project data read"),
                            ("team_read", "Team data read"),
                            ("key_read", "API key data read"),
                            ("key_create", "API key created"),
                            ("key_delete", "API key deleted"),
                            ("key_rotate", "API key rotated"),
                            ("auth_failure", "Authorization check failed"),
                            ("auth_success", "Authorization check passed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Type of resource affected (project, key, team)", max_length=50
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(help_text="ID of the affected resource", max_length=255),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Specific action performed (create, read, delete, rotate)",
                        max_length=50,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=True, help_text="Whether the operation succeeded"),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Additional context (sanitized, no sensitive data)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if operation failed"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the requester", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mcp_audit_log",
                "indexes": [
                    models.Index(
                        fields=["timestamp", "user"], name="mcp_audit_l_timesta_699b3b_idx"
                    ),
                    models.Index(
                        fields=["event_type", "timestamp"], name="mcp_audit_l_event_t_c4a292_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="mcp_audit_l_resourc_b2c665_idx",
                    ),
                ],
            },
        ),
    ]
